### PR TITLE
Extended API to take request parameters, and added 'move' endpoint

### PR DESCRIPTION
**Pull request by horseshoe7**
Should be straightforward.  Followed your API design.  Also cited my upcoming app in the readme.

### CODE REVIEW

**Comment by timonus** [comment]
Hey, thanks for the PR! I'll likely commandeer it and make some modifications if that's alright.

**Comment by horseshoe7** [comment]
please do!  Again, I really appreciate this code.  Simple, no dependencies, but a rock solid foundation for future work.

**Comment by timonus** [comment]
Aww, why thank you :smile:

**Comment by timonus** [comment]
@horseshoe7 closing this in lieu of https://github.com/timonus/TJDropbox/pull/6, please take a look!

**Pull request closed without merging**
